variables:
  TEST_FILE: jmeter-performance-tests.jmx
  HOST: dev1.nrs-ghtr.org.uk

# resources:
#   containers:
#   - container: 'jmetertest'
#     image: 'justb4/jmeter:latest'

jobs:
- job: JMeter_Test
  pool:
    vmImage: ubuntu-latest
  # services:
  #   jmeter: jmetertest
  # displayName: Run JMeter Tests

  steps:
  - task: Docker@1
    displayName: Execute JMeter Tests
    inputs:
      command: run
      containerName: jmetertest
      imageName: justb4/jmeter:latest
      containerCommand: -D log_level.jmeter=DEBUG -J host=$(HOST) -n -t /test/$(TEST_FILE) -l ./test-plan.jtl -j ./jmeter.log -e -o ./report
      runInBackground: false
      workingDirectory: /test
      arguments: -i -v $(Build.SourcesDirectory)/azure/jmeter:/test

  - task: PublishPipelineArtifact@1
    displayName: Publish JMeter Report
    inputs:
      targetPath: azure/jmeter/report
      artifact: jmeter

  - task: AzureFileCopy@3
    displayName: 'AzureBlob File Copy'
    inputs:
      SourcePath: 'azure/jmeter/report'
      azureSubscription: 'azdo.pipelines.cip.S108D.arm10a1d6de-2cee-4f62-b5fa-2cf08d05a1dc'
      Destination: AzureBlob
      storage: s108d01devstr
      ContainerName: '$web'
      BlobPrefix: '$(Build.BuildNumber)'
      outputStorageUri: 'jmeter_reports_url'
