jobs:
- job: jmeter
  pool:
    vmImage: ubuntu-latest
  displayName: Run JMeter tests
  steps:
  - task: CmdLine@2
    continueOnError: false
    displayName: Execute JMeter Tests
    inputs:
      script: 'docker run --rm --name jmeter_test -i -v $PWD:/test -w /test justb4/jmeter:latest \
      -- -Dlog_level.jmeter=DEBUG \
      -Jhost=dev1.nrs-ghtr.org.uk \
      -n -t /test/jmeter-performance-tests.jmx \
      -l ./test-plan.jtl -j ./jmeter.log -e -o ./report'
      workingDirectory: azure/jmeter
  # - task: Bash@3
  #   displayName: Execute JMeter Tests
  #   inputs:
  #     targetType: filePath
  #     filePath: 'azure/jmeter/run.sh'
  #     arguments: '$PWD test/jmeter-performance-tests.jmx $(host)'
  #     workingDirectory: azure/jmeter
  #     failOnStderr: false
  - task: PublishPipelineArtifact@1
    displayName: Publish JMeter Report
    inputs:
      targetPath: azure/jmeter/report
      artifact: jmeter
