trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  IMAGE_NAME: dfedigital/get-help-to-retrain
  postgresUrlPrimary: postgres://test:test@localhost:5432/get-help-to-retrain-primary
  postgresUrlRestricted: postgres://test:test@localhost:5433/get-help-to-retrain-restricted
  BUNDLE_CACHE_FOLDER: $(Pipeline.Workspace)/vendor/bundle

resources:
  containers:
  - container: 'postgres-primary'
    image: 'postgres:11-alpine'
    ports:
      - 5432:5432/tcp
    env:
      POSTGRES_DB: 'get-help-to-retrain-primary'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
  - container: 'postgres-restricted'
    image: 'postgres:11-alpine'
    ports:
      - 5433:5432/tcp
    env:
      POSTGRES_DB: 'get-help-to-retrain-restricted'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
  - container: 'selenium'
    image: 'selenium/standalone-chrome:3'
    ports:
      - 4444:4444/tcp
    volumes:
      - /dev/shm:/dev/shm

stages:
- stage: Checks
  displayName: Run Tests

  jobs:
  - job: Tests
    pool:
      vmImage: 'ubuntu-16.04'
    services:
      postgres_primary: postgres-primary
      postgres_restricted: postgres-restricted
      selenium: selenium

    steps:
      - script: |
          gateway_ip=$(docker network inspect bridge --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}')
          echo "##vso[task.setvariable variable=GatewayIP;]$gateway_ip"
          git_sha=$(git rev-parse --short HEAD)
          echo "##vso[build.updatebuildnumber]$git_sha"
        displayName: 'Set Task Variables'

      - script: |
          sudo apt-get update
          sudo apt-get install libpq-dev bison libgdbm-dev libsqlite3-dev libyaml-dev sqlite3 libreadline6-dev
          gpg --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s -- --autolibs=read-fail
          source /home/vsts/.rvm/scripts/rvm
          rvm install "ruby-2.6.4"
          rvm --default use ruby-2.6.4
          echo "##vso[task.prependpath]$(HOME)/.rvm/rubies/ruby-2.6.4/bin"
        displayName: 'Install dependencies'

      - task: CacheBeta@0
        inputs:
          key: $(Build.SourcesDirectory)/Gemfile.lock
          path: $(BUNDLE_CACHE_FOLDER)
          cacheHitVar: CACHE_RESTORED_BUNDLE
        displayName: Cache bundle

      - script: |
          gem install bundler
          bundle install --jobs=4 --retry=3 --path $(BUNDLE_CACHE_FOLDER) --without development
        displayName: 'bundle install'

      - script: |
          chmod -R +x $(BUNDLE_CACHE_FOLDER)/ruby/2.6.0/bin
        condition: eq(variables.CACHE_RESTORED_BUNDLE, 'true')
        displayName: Restore executable bundle bit
       # Temporary fix for https://github.com/microsoft/azure-pipelines-tasks/issues/10841

      - script: |
          bundle exec rubocop --format clang
        displayName: 'rubocop'

      - script: |
          bundle exec brakeman
        displayName: 'brakeman'

      - script: |
          bundle exec govuk-lint-sass app/webpacker/styles
        displayName: 'GovUK lint'

      - script: |
          yarn install
        displayName: 'yarn install'

      - script: |
          bundle exec rake db:migrate:primary
        displayName: 'Primary Database Setup'
        env:
          RAILS_ENV: test
          PRIMARY_DATABASE_URL: $(postgresUrlPrimary)

      - script: |
          bundle exec rake db:migrate:restricted
        displayName: 'Restricted Database Setup'
        env:
          RAILS_ENV: test
          RESTRICTED_DATABASE_URL: $(postgresUrlRestricted)

      - script: |
          bundle exec rspec --format RspecJunitFormatter --out /build/TEST-rspec.xml
        displayName: 'Run Rspec tests'
        env:
          PRIMARY_DATABASE_URL: $(postgresUrlPrimary)
          RESTRICTED_DATABASE_URL: $(postgresUrlRestricted)
          SELENIUM_REMOTE_ADDRESS: $(GatewayIP)

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          searchFolder: /build/
          testResultsFiles: '*.xml'
          failedTaskOnFailedTest: true

- stage: Build
  displayName: Build image

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: Docker@1
        displayName: Docker Hub login
        inputs:
          command: login
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: DFE-Digital Docker Hub

      - script: docker pull $(IMAGE_NAME):latest || true
        displayName: "Pull latest docker image to cache"

      - script: docker pull $(IMAGE_NAME):assets-latest || true
        displayName: "Pull assets latest docker image to cache"

      - task: Docker@1
        displayName: Build docker assets stage
        inputs:
          command: build
          imageName: $(IMAGE_NAME):assets-latest
          dockerFile: Dockerfile
          arguments: '--cache-from $(IMAGE_NAME):assets-latest --target assets'

      - task: Docker@1
        displayName: Build docker image
        inputs:
          command: build
          imageName: $(IMAGE_NAME):$(Build.BuildNumber)
          dockerFile: Dockerfile
          arguments: '--cache-from=$(IMAGE_NAME):assets-latest,$(IMAGE_NAME):latest'

      - task: Docker@2
        displayName: Push new image with current tag
        inputs:
          command: push
          repository: $(IMAGE_NAME)
          tags: $(Build.BuildNumber)

      - task: Docker@2
        displayName: Push new image with assets tag
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: push
          repository: $(IMAGE_NAME)
          tags: assets-latest

      - task: Docker@2
        displayName: Push tagged image (latest) if master
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: push
          repository: $(IMAGE_NAME)
          tags: latest

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          Contents: |
            azure/**
          TargetFolder: '$(build.artifactstagingdirectory)'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'ARMTemplates'

- stage: Deployment
  displayName: Deployment
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

  jobs:
    - job: QA
      displayName: Deploy to QA
      pool:
        vmImage: 'vs2017-win2016'

      variables:
        - group: 'Release Common'

      steps:
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on $(resourceEnvironmentName)-$(serviceName)'
          inputs:
            action: 'Create Or Update Resource Group'
            location: 'West Europe'
            azureSubscription: azdo.pipelines.cip.S108T.arm282af598-0480-4a28-ab29-efa10624365a
            resourceGroupName: s108t01-qa
            csmFile: './azure/template.json'
            csmParametersFile: './azure/config/qa.parameters.json'
            overrideParameters: '-containerImageReference $(IMAGE_NAME):$(Build.BuildNumber) -supportEmailAddresses $(supportEmailAddresses)'
            deploymentOutputs: DeploymentOutput

        - task: RasmusWatjen.ARMOutputParserExtension.ARMOutputConverter.ARMOutputParserExtension@1
          displayName: 'Parse ARM Deployment Outputs into variables'
          inputs:
            armOutput: $(DeploymentOutput)
            variablePrefix: arm_

        - script: |
            env
          displayName: 'debug'

        - task: AzureAppServiceManage@0
          displayName: 'Start Azure App Service: QA'
          inputs:
            azureSubscription: azdo.pipelines.cip.S108T.arm282af598-0480-4a28-ab29-efa10624365a
            Action: 'Start Azure App Service'
            WebAppName: $(arm_appServiceName)
            SpecifySlotOrASE: true
            resourceGroupName: s108t01-qa
            Slot: staging

        - task: AzureAppServiceManage@0
          displayName: 'Swap Slots: QA'
          inputs:
            azureSubscription: azdo.pipelines.cip.S108T.arm282af598-0480-4a28-ab29-efa10624365a
            WebAppName: $(arm_appServiceName)
            resourceGroupName: 's108t01-qa'
            SourceSlot: staging

        - task: AzureAppServiceManage@0
          displayName: 'Stop Azure App Service: QA'
          inputs:
            azureSubscription: azdo.pipelines.cip.S108T.arm282af598-0480-4a28-ab29-efa10624365a
            Action: 'Stop Azure App Service'
            WebAppName: $(arm_appServiceName)
            SpecifySlotOrASE: true
            resourceGroupName: s108t01-qa
            Slot: staging
