default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: get_help_to_retrain_development
  restricted:
    <<: *default
    database: get_help_to_retrain_restricted_development
    migrations_paths: db/restricted_migrate

test: &test
  primary:
    <<: *default
    database: get_help_to_retrain_test
    url: <%= ENV['PRIMARY_DATABASE_URL'] %>
  restricted:
    <<: *default
    database: get_help_to_retrain_restricted_test
    migrations_paths: db/restricted_migrate
    url: <%= ENV['RESTRICTED_DATABASE_URL'] %>

cucumber:
  <<: *test

production:
  primary:
    <<: *default
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['DB_DATABASE'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    url: <%= ENV['HEROKU_APP_NAME'].present? ? ENV['DATABASE_URL'] : ENV['PRIMARY_DATABASE_URL']  %>
  restricted:
    <<: *default
    host: <%= ENV['RESTRICTED_DB_HOST'] %>
    database: <%= ENV['RESTRICTED_DB_DATABASE'] %>
    username: <%= ENV['RESTRICTED_DB_USERNAME'] %>
    password: <%= ENV['RESTRICTED_DB_PASSWORD'] %>
    url: <%= ENV['HEROKU_APP_NAME'].present? ? ENV['DATABASE_URL'] : ENV['RESTRICTED_DATABASE_URL']  %>
    migrations_paths: db/restricted_migrate

