inherit_from: ../.rubocop.yml

require: rubocop-rspec

Style/BlockDelimiters:
  Exclude:
  - factories/**/*.rb
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
